# Copyright (C) 2025 Infineon Technologies
# SPDX-License-Identifier: Apache-2.0

manifest:
  projects:
    - name: infineon-mcuboot
      url: https://github.com/mcu-tools/mcuboot
      revision: v1.9.4-cypress
      path: infineon-mcuboot
      submodules: true
